// my-vue-content-app/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <br-page :configuration="configuration" :mapping="mapping">
      <main>
        <br-component component="main"/>
      </main>
    </br-page>
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import axios from "axios";
import Content from "./components/Content";
import MyComponent from "./components/MyComponent";
import Banner from "./components/Banner";

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  data: () => {
    return {
      configuration: {
        path: `${window.location.pathname}${window.location.search}`,
        endpoint: 'https://sandbox-sales02.bloomreach.io/delivery/site/v1/channels/getting-started/pages',
        httpClient: axios,
      },
      mapping: {Content, MyComponent, Banner}
    };
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// my-react-content-app/src/App.js
import logo from './logo.svg';
import './App.css';
import axios from "axios";
import {BrPage} from "@bloomreach/react-sdk";
import {Content} from "./components/Content";
import {MyComponent} from "./components/MyComponent";
import {Banner} from "./components/Banner";

function App() {
    return (
        <div className="App">
            <header className="App-header">
                <img src={logo} className="App-logo" alt="logo"/>
                <p>
                    Edit <code>src/App.js</code> and save to reload.
                </p>
                <BrPage configuration={{
                    path: `${window.location.pathname}${window.location.search}`,
                    endpoint: 'https://sandbox-sales02.bloomreach.io/delivery/site/v1/channels/getting-started/pages',
                    httpClient: axios
                }} mapping={{Content, MyComponent, Banner}}>
                </BrPage>
            </header>
        </div>
    );
}

export default App;
