// my-vue-content-app/src/components/Content.vue
<template>
  <div>
    <div>
      <h1>{{ document.title }}</h1>
      <p>{{ document.introduction }}</p>
      <div v-if="document.content" v-html="page.rewriteLinks(page.sanitize(document.content.value))"/>
    </div>
  </div>
</template>

<script>
export default {
  computed: {
    document() {
      return this.page.getDocument().getData();
    },
  },
  props: ['component', 'page']
}

</script>

// my-angular-content-app/src/app/components/content/content.component.ts
import {Component, Input} from '@angular/core';
import {Component as BrComponent, Document, Page,} from "@bloomreach/spa-sdk";

@Component({
  selector: 'app-content',
  templateUrl: './content.component.html',
})
export class ContentComponent {

  @Input() component!: BrComponent;
  @Input() page!: Page;

  get document() {
    return this.page.getDocument<Document>()?.getData<any>();
  }

}

<div *ngIf="document">
  <h3>{{document.title}}</h3>
  <p>{{document.introduction}}</p>
  <div
    *ngIf="document?.content"
    [innerHTML]="page.rewriteLinks(page.sanitize(document!.content!.value))"
  ></div>
</div>
