// my-vue-content-app/src/components/SharedBanner.vue
<template>
  <div style="background-color: grey; color: white; padding: 10px; position: relative">
    <br-manage-content-button :content="document" />
    <h2>{{ content.title }}</h2>
    <div v-html="content.text.value"></div>
    <img :src="imageSrc"/>
    <p><a :href=link>{{content.ctalabel}}</a></p>
  </div>
</template>
<script>
export default {
  computed: {
    document() {
      return this.page?.getContent(this.component.getProperties()?.document);
    },
    content() {
      return this.document?.getData();
    },
    imageSrc() {
      return this.page?.getContent(this.content.image)?.getOriginal()?.getUrl();
    },
    link() {
      return this.page?.getContent(this.content.ctalink)?.getUrl();
    },
  },
  props: ['component', 'page']
}
</script>

// my-react-content-app/src/components/SharedBanner.jsx
import {BrManageContentButton} from "@bloomreach/react-sdk";

export function SharedBanner({component, page}) {

    const properties = component.getProperties();
    const content = properties.document && page.getContent(properties.document)?.getData();

    if (!content) {
        return <p>No Banner reference set</p>
    }

    return (
        <div style={{backgroundColor: "grey", padding: '10px', position: 'relative'}}>
            <BrManageContentButton content={page.getContent(properties.document)}/>
            <h2>{content.title}</h2>
            <div dangerouslySetInnerHTML={{__html: content.text.value}}/>
            <img src={page.getContent(content.image).getOriginal().getUrl()}/>
            <p><a href={page.getContent(content.ctalink).getUrl()}>{content.ctalabel}</a></p>
        </div>
    );
}
