// my-angular-content-app/src/app/components/banner/banner.component.ts
import {Component, Input} from '@angular/core';
import {ContainerItem as BrComponent, ImageSet, Page, Reference,} from "@bloomreach/spa-sdk";

@Component({
  selector: 'app-banner',
  templateUrl: './banner.component.html',
})
export class BannerComponent {

  @Input() component!: BrComponent;
  @Input() page!: Page;
  safeHTML?: Promise<string | null>;


  get content() {
    return this.component.getContent<BannerComponentModel>(this.page);
  }

  get imageSrc() {
    return this.content && this.page.getContent<ImageSet>(this.content.image)?.getOriginal()?.getUrl();
  }

  get link() {
    return this.content && this.page.getContent(this.content.ctalink)?.getUrl();
  }

}

interface BannerComponentModel {
  title: string
  text: { value: string }
  image: Reference
  ctalabel: string
  ctalink: Reference
  //contentType: string
}

<div style="background-color: grey; color: white; padding: 10px">
  <h2>{{ content?.title }}</h2>
  <div *ngIf="content?.text" [innerHTML]="content?.text?.value"></div>
  <img src="{{imageSrc}}" />
  <p><a href="{{link}}">{{content?.ctalabel}}</a></p>
</div>

// my-vue-content-app/src/components/Banner.vue
<template>
  <div style="background-color: grey; color: white; padding: 10px">
    <h2>{{ content.title }}</h2>
    <div v-html="content.text.value"></div>
    <img :src="imageSrc"/>
    <p><a :href=link>{{content.ctalabel}}</a></p>
  </div>
</template>
<script>
export default {
  computed: {
    content() {
      return this.component.getContent(this.page);
    },
    imageSrc() {
      return this.page.getContent(this.content.image).getOriginal().getUrl();
    },
    link() {
      return this.page.getContent(this.content.ctalink).getUrl();
    },
  },
  props: ['component', 'page']
}
</script>
