// my-react-content-app/src/components/Content.jsx
export function Content({component, page}) {

    const document = page.getDocument();

    const {title, content, introduction} = document.getData();

    return (
        <div>
            <h1>{title}</h1>
            <p>{introduction}</p>
            <div dangerouslySetInnerHTML={{__html: content.value}}/>
        </div>
    );
}

// my-vue-content-app/src/components/Content.vue
<template>
  <div>
    <div>
      <h1>{{ document.title }}</h1>
      <p>{{ document.introduction }}</p>
      <div v-if="document.content" v-html="page.rewriteLinks(page.sanitize(document.content.value))"/>
    </div>
  </div>
</template>

<script>
export default {
  computed: {
    document() {
      return this.page.getDocument().getData();
    },
  },
  props: ['component', 'page']
}

</script>
