// my-vue-content-app/src/components/SharedBanner.vue
<template>
  <div style="background-color: grey; color: white; padding: 10px; position: relative">
    <br-manage-content-button :content="document" />
    <h2>{{ content.title }}</h2>
    <div v-html="content.text.value"></div>
    <img :src="imageSrc"/>
    <p><a :href=link>{{content.ctalabel}}</a></p>
  </div>
</template>
<script>
export default {
  computed: {
    document() {
      return this.page?.getContent(this.component.getProperties()?.document);
    },
    content() {
      return this.document?.getData();
    },
    imageSrc() {
      return this.page?.getContent(this.content.image)?.getOriginal()?.getUrl();
    },
    link() {
      return this.page?.getContent(this.content.ctalink)?.getUrl();
    },
  },
  props: ['component', 'page']
}
</script>

// my-angular-content-app/src/app/components/sharedbanner/sharedbanner.component.ts
import {Component, Input} from '@angular/core';
import {ContainerItem as BrComponent, Content, ImageSet, Page, Reference,} from "@bloomreach/spa-sdk";

@Component({
  selector: 'app-shared-banner',
  templateUrl: './sharedbanner.component.html',
})
export class SharedBannerComponent {

  @Input() component!: BrComponent;
  @Input() page!: Page;
  safeHTML?: Promise<string | null>;

  get document() {
    return this.page.getContent<Content>(this.component.getProperties<{ document: Reference }>().document);
  }

  get content() {
    return this.document?.getData<BannerDocumentModel>();
  }

  get imageSrc() {
    return this.content && this.page.getContent<ImageSet>(this.content.image)?.getOriginal()?.getUrl();
  }

  get link() {
    return this.content && this.page.getContent(this.content.ctalink)?.getUrl();
  }

}

interface BannerDocumentModel {
  title: string
  text: { value: string }
  image: Reference
  ctalabel: string
  ctalink: Reference
  //contentType: string
}

<div style="background-color: grey; color: white; padding: 10px; position: relative">
  <ng-container [brManageContentButton]="document"></ng-container>
  <h2>{{ content?.title }}</h2>
  <div *ngIf="content?.text" [innerHTML]="content?.text?.value"></div>
  <img src="{{imageSrc}}" />
  <p><a href="{{link}}">{{content?.ctalabel}}</a></p>
</div>
